name = "RowPredicates"
version = "0.1.0"
defaultTargets = ["rowpredicates"]

[[lean_lib]]
name = "RowPredicates"

[[lean_exe]]
name = "rowpredicates"
root = "Main"

[[require]]
name = "aesop"
git = "https://github.com/leanprover-community/aesop"