name = "Rope"
version = "0.1.0"
defaultTargets = ["rope"]

[[lean_lib]]
name = "Rope"

[[lean_exe]]
name = "rope"
root = "Main"

[[require]]
name = "aesop"
git = "https://github.com/leanprover-community/aesop"